version: '3.7'

services:

  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=9121
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  database_test:
    image: postgres
    container_name: database_test
    restart: always
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=9121
      - POSTGRES_DB=rentx_test
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
      - database_test
    depends_on:
      - database
      - database_test
volumes:
  pgdata:
    driver: local
